---
test:
  ansible_tower_defaults: &ansible_tower_defaults
    url: https://dev-ansible-tower3.example.com/api/v1/
    user: testuser
    password: secret
  ansible_tower:
    <<: *ansible_tower_defaults
